export const PROJECT_CATEGORIES = [
  { value: "tech", label: "Informatique et technologie" },
  { value: "mobile", label: "Application mobile" },
  { value: "web", label: "Site internet" },
  { value: "cloud", label: "Informatique Cloud et Big Data" },
  { value: "ai", label: "Intelligence Artificielle et Machine Learning" },
  { value: "blockchain", label: "Blockchain et Cryptomonnaies" },
  { value: "robotics", label: "Robotique" },
  { value: "marketing", label: "Marketing et Publicité" },
  { value: "design", label: "Design et Création" },
  { value: "hr", label: "Ressources humaines" },
  { value: "finance", label: "Finance et Comptabilité" },
  { value: "sales", label: "Vente et Développement Commercial" },
  { value: "health", label: "Santé" },
  { value: "engineering", label: "Ingénierie" },
  { value: "education", label: "Éducation" },
  { value: "legal", label: "Droit" },
  { value: "entrepreneurship", label: "Entrepreneuriat" },
  { value: "architecture", label: "Architecture" },
  { value: "media", label: "Médias et Communication" },
  { value: "logistics", label: "Logistique et Transport" },
  { value: "research", label: "Recherche et développement" },
  { value: "project", label: "Gestion de Projet" },
  { value: "industry", label: "Industrie et Production" },
  { value: "consulting", label: "Conseil" },
  { value: "tourism", label: "Hôtellerie et Tourisme" },
  { value: "agriculture", label: "Agriculture et Agroalimentaire" },
  { value: "energy", label: "Énergie et environnement" },
  { value: "realestate", label: "Immobilier" },
  { value: "culture", label: "Art et Culture" },
  { value: "social", label: "Sciences Sociales" },
  { value: "telecom", label: "Télécommunications" },
  { value: "security", label: "Sécurité et Défense" },
  { value: "public", label: "Administration publique" },
  { value: "pr", label: "Relations Publiques" },
  { value: "biotech", label: "Biotechnologie et Pharmaceutique" },
  { value: "sports", label: "Sports et Loisirs" },
  { value: "events", label: "Événementiel" },
  { value: "transport", label: "Transports et Mobilité" },
  { value: "medical", label: "Médical et paramédical" },
  { value: "it", label: "Systèmes d'information" },
  { value: "retail", label: "Commerce de détail" },
  { value: "food", label: "Restauration" },
  { value: "fashion", label: "Mode et Textile" },
  { value: "trade", label: "Commerce international" },
  { value: "ecommerce", label: "Commerce électronique" },
  { value: "gaming", label: "Jeux vidéo et eSports" },
  { value: "social_media", label: "Réseaux Sociaux et Influenceurs" },
  { value: "aerospace", label: "Aéronautique et Spatiale" }
] as const;
